In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 데이터 만들기
np.random.seed(42)

x1 = np.linspace(0, 10, 50)
x2 = 2 * x1 + 1 + np.random.normal(0, 2, 50)

X = np.column_stack([x1, x2]) # 2차원 데이터

plt.scatter(X[:, 0], X[:, 1])
plt.xlabel("feature 1")
plt.ylabel("feature 2")
plt.title("Original 2D data")
plt.grid()

In [39]:
# 1. 평균 제거
X_mean = np.mean(X, axis=0)
X_centered = X - X_mean

# 2. 공분산 행렬
cov_matrix = np.cov(X_centered, rowvar=False)

# 3. 고유값, 고유벡터
eigvals, eigvecs = np.linalg.eig(cov_matrix)

# 4. 고유값 큰 순서대로 정렬
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

# 5. 첫 번째 주성분 선택
pc1 = eigvecs[:, 0]

# 6. 1차원으로 투영
X_pca_1d = X_centered @ pc1

print("평균:", X_mean)
print("공분산 행렬:\n", cov_matrix)
print("고유값:", eigvals)
print("고유벡터:\n", eigvecs)
print("1차원 PCA 결과:\n", X_pca_1d[:5])

explained_variance_ratio = eigvals / np.sum(eigvals)

print("설명 분산 비율:", explained_variance_ratio)
print("PC1이 설명하는 비율:", explained_variance_ratio[0])

평균: [ 5.         10.54905219]
공분산 행렬:
 [[ 8.85047897 16.67459622]
 [16.67459622 34.78341858]]
고유값: [42.93972081  0.69417674]
고유벡터:
 [[-0.4393961  -0.89829342]
 [-0.89829342  0.4393961 ]]
1차원 PCA 결과:
 [ 9.88244114 10.56691202  8.69855645  6.66960671  9.37021592]
설명 분산 비율: [0.98409088 0.01590912]
PC1이 설명하는 비율: 0.9840908838865159
